### ISSUE TITLE
ENH: Scrape request and notes

### ISSUE THREAD

**Issue by akaahanui** [DataKind-DC/capital-nature-ingest#167] opened 2019-11-02 05:03 UTC
HI Scott - Stella and I were reviewing the last scrape. Thanks for pulling. We'd like to run the scrapers again at your convenience with some adjustments based on our observations/requests listed below.

Question: does each scraper have the date duration programmed individually? For example, some orgs had only October or early November and others were well into 2020. (For Arlington Parks we deleted 77 events after Feb 2020)

For this re-scrape, please pull events from Nov 1 through the end of February 2020, realizing that some orgs may not have many events listed yet.

We noticed 11 orgs were scraped. Were the others not scrapable/had errors?

## Expected Behavior
1) Can these orgs have the States pulled for the descriptions? (DC) (MD (VA)
- Casey Trees
- Audubon Naturalist
- NPS
- Virginia Native Plant Society

2) For NPS events, we made progress on this last run with the exclusion of parks that are too far away. We'd still like to exclude the following:
- Hampton National Historic Site
- Harpers Ferry National Historical Park
- Shenandoah National Park

We'd like to include NPS Rock Creek Park if possible.

## Context
We feel that if these edits are made in the re-scrape it will cut down our curation time and provide events with dates in a better time range.

Once we have the log of what's being scraped, we can make sure our manual volunteers are not doing double duty.

Thanks and please let me know if you have any questions!

**Comment by csmcallister** [comment] 2020-01-10 22:42
Just now getting around to this one @akaahanui 

For the state abbreviations, is this ask a dupe of #104 ?

For the parks to exclude, this seems like a dupe of #106. 

If those other issues cover what's being asked in here, let me know so I can close this issue and we can discuss in the respective issues.

**Comment by csmcallister** [comment] 2020-01-22 00:14
Closing this @akaahanui since I believe the issues within are dupes like I mentioned above.

**Closed by csmcallister** 2020-01-22 00:14 UTC
Labels: enhancement, question
