### ISSUE TITLE
Event CSV Templates

### ISSUE THREAD

**Issue by bmvoss** [DataKind-DC/capital-nature-ingest#29] opened 2019-01-24 01:33 UTC
In order for Event Organizer and Venue information to appear properly for an event, the info for these values must be a perfect match for an Organizer Name and a Venue Name in the corresponding CSV files.

## Expected Behavior
If the Event Organizer and Event Venue Name are typed exactly the same in all event CSV files uploaded to Wordpress, the plugin will link the info across the files and they will appear on the website when you are looking at an individual event page.

## Current Behavior
Sometimes there are inconsistencies in how Organizer or Venue Names are spelled. We need to ensure that these are always identical across all the CSV files.

## Possible Solution
Check if the Organizer Name or Venue Name in your scraped events file already exists by looking on the Wordpress admin page:

- Organizers: http://capitalnature.org/wp-admin/edit.php?post_type=tribe_organizer
- Venues: http://capitalnature.org/wp-admin/edit.php?post_type=tribe_venue

If the Organizer or Venue for your Events file is not already listed, add it. Make sure it appears in your CSV file *EXACTLY* as it is shown in the list.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
When uploading events for the January 15th website launch, we discovered that Organizer and Venue CSV files have to be uploaded before the events CSV file(s) are uploaded in order for everything to link properly and display the full info for each event. We have not tested this yet, but I think we can avoid this issue moving forward by simply adding new Venue or Organizer names manually through the Wordpress admin site rather than uploading new Organizer and Venue CSV files every time a change has to be made (although this might be more efficient if major changes are ever needed).

**Comment by csmcallister** [comment] 2019-01-25 19:46
@bmvoss I tried logging in to view the organizers and venues but was met with this: 

![screen shot 2019-01-25 at 2 45 19 pm](https://user-images.githubusercontent.com/33464354/51769002-db2c7400-20af-11e9-903b-716b11639e84.png)

**Comment by bmvoss** [comment] 2019-01-29 18:50
@csmcallister In the other thread I suggested logging in at http://capitalnature.org/wp-admin/ first, not sure if that makes a difference. Otherwise, maybe @ratherironic has a suggestion - does Scott need new credentials?

**Comment by csmcallister** [comment] 2019-02-10 15:07
Any update @ratherironic ?

I'll soon merge all of the event scripts into one, which will generate a single csv with all of the events. That'll give a list of organizers and venues to add to the lists.

**Comment by ratherironic** [comment] 2019-02-11 04:16
@csmcallister Sorry for the delay. Were you able to login via http://capitalnature.org/wp-admin/ ? 
I believe that is required. If you don't have a working login please reach out to me via email and I can send over some login credentials.

**Comment by csmcallister** [comment] 2019-02-11 11:55
I’m able to login using the Guest account y’all created for us, but I still receive that access error when I try to view the venue and organizer pages after logging in. I’ve also tried to navigate to those pages from within my admin dashboard, but can’t see how to. Perhaps the Guest account permissions aren’t scoped right?

**Comment by csmcallister** [comment] 2019-03-16 01:02
I think this is a duplicate of #56 @bmvoss 

If so, can we close?

**Comment by bmvoss** [comment] 2019-03-17 15:30
@csmcallister Huh, not sure why I created two of these. Yes, go ahead and close this one.

**Closed** 2019-03-18 10:10 UTC
Labels: question
